# Generated by Django 5.2.8 on 2025-11-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_matchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhistory',
            name='matched_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='missing_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='resume_full',
            field=models.TextField(blank=True, null=True),
        ),
    ]
